name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install docs dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/docs.txt
    - name: Run sphinx
      run: |
        sphinx-build -b html docs/ docs/_build
        touch docs/_build/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/ # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch